const ORDER_STATUS = {
  PLACED: 'PLACED',
  CANCELED: 'CANCELED',
  PROCESSING: 'PROCESSING',
  IN_ROUTE: 'IN_ROUTE',
  DELIVERED: 'DELIVERED',
  RECEIVED: 'RECEIVED',
};

module.exports = ORDER_STATUS;
